[phases.setup]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate && python setup_admin.py && gunicorn mysite.wsgi:application"